<a href="https://colab.research.google.com/github/ishita91989/N_test/blob/main/NurturevAssign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Write a python code to find out the following:

## A
Which account has the biggest decline in Sales team over the last 6 months ?
Should we consider the absolute or relative decline ? Why ?

In [36]:
import pandas as pd

In [37]:
df = pd.read_csv('/content/sample_data/pdl_file.csv')
df.head()

,id,domain_name,ticker,mic_exchange,summary,name,linkedin_url,profiles,tags,employee_count,...,employee_growth_rate,employee_count_by_month,employee_count_by_month_by_role,employee_count_by_country,top_previous_employers_by_role,top_next_employers_by_role,employee_count_by_month_by_level,recent_exec_hires,recent_exec_departures,created_at
0,uCZ0oMvCJnic2DHtCHVhKgz3V133,hellosign.com,NaN,NaN,hellosign is now dropbox sign! \nplease follow...,hellosign,linkedin.com/company/hellosign,"['linkedin.com/company/hellosign', 'linkedin.c...","['mobile payments', 'saas', 'workflow content ...",27,...,"{'3_month': 0.0, '6_month': -0.0357, '12_month...","{'2010-01': 2, '2010-02': 2, '2010-03': 2, '20...","{'2010-01': {'real_estate': 0, 'design': 0, 't...","{'united states': 26, 'australia': 1}","{'all': {'cpxKO1dSuPawCTCn8FZpOAYPM0lF': 27, '...","{'all': {'cpxKO1dSuPawCTCn8FZpOAYPM0lF': 75, '...","{'2010-01': {'entry': 1, 'unpaid': 0, 'senior'...",[],[],2024-08-06 14:51:23
1,34xfZ363o8JiC0StuwJOVQ2pizC6,unilever.com,ULVRN.MX,xmex,"be part of the world’s most successful, purpos...",unilever,linkedin.com/company/unilever,"['linkedin.com/company/unilever', 'linkedin.co...","['purpose', 'retail', 'food', 'refreshments', ...",85424,...,"{'3_month': -0.0036, '6_month': -0.0044, '12_m...","{'2010-01': 61753, '2010-02': 62109, '2010-03'...","{'2010-01': {'real_estate': 13, 'design': 244,...","{'india': 12469, 'brazil': 7438, 'united kingd...","{'all': {'PaCiblC4ZtUzQ6LHC8aj4AorHkCI': 4791,...","{'all': {'PaCiblC4ZtUzQ6LHC8aj4AorHkCI': 5477,...","{'2010-01': {'entry': 373, 'unpaid': 2, 'senio...","[{'joined_date': '2024-04', 'pdl_id': 'jzkZPOm...","[{'departed_date': '2024-04', 'pdl_id': 'jzkZP...",2024-08-06 14:51:23
2,xb4kCql1z8vnhE6lt7HozwTqo939,vmware.com,VMW,xnys,vmware is a leading provider of multi-cloud se...,vmware,linkedin.com/company/vmware,"['linkedin.com/company/vmware', 'linkedin.com/...","['cloud infrastructure', 'software-defined dat...",26202,...,"{'3_month': -0.0663, '6_month': -0.2483, '12_m...","{'2010-01': 8145, '2010-02': 8254, '2010-03': ...","{'2010-01': {'real_estate': 12, 'design': 50, ...","{'united states': 9615, 'india': 6886, 'bulgar...","{'all': {'EyWCGfUy1Xf29qBoP2TW8ATRRvMt': 5298,...","{'all': {'fOtlxmIhKJiDeNOZ45XQLQxdVBrf': 2897,...","{'2010-01': {'entry': 1, 'unpaid': 1, 'senior'...","[{'joined_date': '2024-02', 'pdl_id': 'IiYh9ES...","[{'departed_date': '2024-02', 'pdl_id': 'cmnEz...",2024-08-06 14:51:23
3,eNoRZQzcsn1b9Mtcjer5dgF5NPj5,medtronic.com,MDT,xnys,a global healthcare technology leader — boldly...,medtronic,linkedin.com/company/medtronic,"['linkedin.com/company/medtronic', 'linkedin.c...","['http://www.facebook.com/medtroniccareers', '...",61216,...,"{'3_month': -0.0006, '6_month': 0.0022, '12_mo...","{'2010-01': 28739, '2010-02': 28888, '2010-03'...","{'2010-01': {'real_estate': 8, 'design': 233, ...","{'united states': 32427, 'india': 2290, 'irela...","{'all': {'n5njossQ6s8vn5HECjUe8gZPDVOO': 4916,...","{'all': {'uOaURw7XalPswFBqDiMaCgfewoLz': 3878,...","{'2010-01': {'entry': 16, 'unpaid': 3, 'senior...","[{'joined_date': '2024-04', 'pdl_id': 'Vzn-ykU...","[{'departed_date': '2024-03', 'pdl_id': 'cbvxD...",2024-08-06 14:51:23
4,Aefrg8G2hrDQqAhlxtUnvAWdP097,novartis.com,NVS,xnys,novartis provides healthcare solutions that im...,novartis,linkedin.com/company/novartis,"['linkedin.com/company/novartis', 'linkedin.co...","['generic medicines and biosimilars', 'data & ...",59723,...,"{'3_month': -0.0021, '6_month': -0.0108, '12_m...","{'2010-01': 49668, '2010-02': 49918, '2010-03'...","{'2010-01': {'real_estate': 8, 'design': 73, '...","{'united states': 13595, 'india': 8176, 'switz...","{'all': {'w9C0Znhx6QgUFVBDCwL5kQhGY93j': 9522,...","{'all': {'KxWnnuFp5BMWIUgJFRFX3gAzDdya': 8686,...","{'2010-01': {'entry': 146, 'unpaid': 0, 'senio...","[{'joined_date': '2024-05', 'pdl_id': 'Z9PXG4V...","[{'departed_date': '2024-02', 'pdl_id': 'PmyjN...",2024-08-06 14:51:23

In [38]:
pd.read_csv('/content/sample_data/pdl_file.csv', nrows = 15)

,id,domain_name,ticker,mic_exchange,summary,name,linkedin_url,profiles,tags,employee_count,...,employee_growth_rate,employee_count_by_month,employee_count_by_month_by_role,employee_count_by_country,top_previous_employers_by_role,top_next_employers_by_role,employee_count_by_month_by_level,recent_exec_hires,recent_exec_departures,created_at
0,uCZ0oMvCJnic2DHtCHVhKgz3V133,hellosign.com,NaN,NaN,hellosign is now dropbox sign! \nplease follow...,hellosign,linkedin.com/company/hellosign,"['linkedin.com/company/hellosign', 'linkedin.c...","['mobile payments', 'saas', 'workflow content ...",27,...,"{'3_month': 0.0, '6_month': -0.0357, '12_month...","{'2010-01': 2, '2010-02': 2, '2010-03': 2, '20...","{'2010-01': {'real_estate': 0, 'design': 0, 't...","{'united states': 26, 'australia': 1}","{'all': {'cpxKO1dSuPawCTCn8FZpOAYPM0lF': 27, '...","{'all': {'cpxKO1dSuPawCTCn8FZpOAYPM0lF': 75, '...","{'2010-01': {'entry': 1, 'unpaid': 0, 'senior'...",[],[],2024-08-06 14:51:23
1,34xfZ363o8JiC0StuwJOVQ2pizC6,unilever.com,ULVRN.MX,xmex,"be part of the world’s most successful, purpos...",unilever,linkedin.com/company/unilever,"['linkedin.com/company/unilever', 'linkedin.co...","['purpose', 'retail', 'food', 'refreshments', ...",85424,...,"{'3_month': -0.0036, '6_month': -0.0044, '12_m...","{'2010-01': 61753, '2010-02': 62109, '2010-03'...","{'2010-01': {'real_estate': 13, 'design': 244,...","{'india': 12469, 'brazil': 7438, 'united kingd...","{'all': {'PaCiblC4ZtUzQ6LHC8aj4AorHkCI': 4791,...","{'all': {'PaCiblC4ZtUzQ6LHC8aj4AorHkCI': 5477,...","{'2010-01': {'entry': 373, 'unpaid': 2, 'senio...","[{'joined_date': '2024-04', 'pdl_id': 'jzkZPOm...","[{'departed_date': '2024-04', 'pdl_id': 'jzkZP...",2024-08-06 14:51:23
2,xb4kCql1z8vnhE6lt7HozwTqo939,vmware.com,VMW,xnys,vmware is a leading provider of multi-cloud se...,vmware,linkedin.com/company/vmware,"['linkedin.com/company/vmware', 'linkedin.com/...","['cloud infrastructure', 'software-defined dat...",26202,...,"{'3_month': -0.0663, '6_month': -0.2483, '12_m...","{'2010-01': 8145, '2010-02': 8254, '2010-03': ...","{'2010-01': {'real_estate': 12, 'design': 50, ...","{'united states': 9615, 'india': 6886, 'bulgar...","{'all': {'EyWCGfUy1Xf29qBoP2TW8ATRRvMt': 5298,...","{'all': {'fOtlxmIhKJiDeNOZ45XQLQxdVBrf': 2897,...","{'2010-01': {'entry': 1, 'unpaid': 1, 'senior'...","[{'joined_date': '2024-02', 'pdl_id': 'IiYh9ES...","[{'departed_date': '2024-02', 'pdl_id': 'cmnEz...",2024-08-06 14:51:23
3,eNoRZQzcsn1b9Mtcjer5dgF5NPj5,medtronic.com,MDT,xnys,a global healthcare technology leader — boldly...,medtronic,linkedin.com/company/medtronic,"['linkedin.com/company/medtronic', 'linkedin.c...","['http://www.facebook.com/medtroniccareers', '...",61216,...,"{'3_month': -0.0006, '6_month': 0.0022, '12_mo...","{'2010-01': 28739, '2010-02': 28888, '2010-03'...","{'2010-01': {'real_estate': 8, 'design': 233, ...","{'united states': 32427, 'india': 2290, 'irela...","{'all': {'n5njossQ6s8vn5HECjUe8gZPDVOO': 4916,...","{'all': {'uOaURw7XalPswFBqDiMaCgfewoLz': 3878,...","{'2010-01': {'entry': 16, 'unpaid': 3, 'senior...","[{'joined_date': '2024-04', 'pdl_id': 'Vzn-ykU...","[{'departed_date': '2024-03', 'pdl_id': 'cbvxD...",2024-08-06 14:51:23
4,Aefrg8G2hrDQqAhlxtUnvAWdP097,novartis.com,NVS,xnys,novartis provides healthcare solutions that im...,novartis,linkedin.com/company/novartis,"['linkedin.com/company/novartis', 'linkedin.co...","['generic medicines and biosimilars', 'data & ...",59723,...,"{'3_month': -0.0021, '6_month': -0.0108, '12_m...","{'2010-01': 49668, '2010-02': 49918, '2010-03'...","{'2010-01': {'real_estate': 8, 'design': 73, '...","{'united states': 13595, 'india': 8176, 'switz...","{'all': {'w9C0Znhx6QgUFVBDCwL5kQhGY93j': 9522,...","{'all': {'KxWnnuFp5BMWIUgJFRFX3gAzDdya': 8686,...","{'2010-01': {'entry': 146, 'unpaid': 0, 'senio...","[{'joined_date': '2024-05', 'pdl_id': 'Z9PXG4V...","[{'departed_date': '2024-02', 'pdl_id': 'PmyjN...",2024-08-06 14:51:23
5,xCM2TWzBm338vM9B2uy3Wg9Isagg,nikon.com,NaN,NaN,ニコンは、100年の歴史で培ってきた「光利用技術」と「精密技術」をもとに、多彩な技術・製品・...,nikon,linkedin.com/company/nikon,"['linkedin.com/company/nikon', 'linkedin.com/c...",NaN,901,...,"{'3_month': 0.0045, '6_month': 0.0146, '12_mon...","{'2010-01': 760, '2010-02': 756, '2010-03': 76...","{'2010-01': {'real_estate': 0, 'design': 15, '...","{'japan': 239, 'united states': 170, 'united k...","{'all': {'0S9Cqq5OyDOR5HsCoOXMswSYfAui': 52, '...","{'all': {'WwsvpK6OUldRqD2CRa2U1ARzIOXG': 64, '...","{'2010-01': {'entry': 6, 'unpaid': 0, 'senior'...","[{'joined_date': '2024-04', 'pdl_id': 'jZ56wXL...",[],2024-08-06 14:51:23
6,KD9BQs0okCAcyDmQBBREiwd8hyhN,acceleronpharma.com,XLRN,xnas,"effective 11/22/21, acceleron pharma inc. is n...",acceleron pharma,linkedin.com/company/acceleron-pharma,"['linkedin.com/company/acceleron-pharma', 'lin...","['science and engineering', 'health care', 'sm...",69,...,"{'3_month': 0.0, '6_month': -0.0143, '12_month...","{'2010-01': 178, '2010-02': 177, '2010-03': 17...","{'2010-01': {'real_estate': 0, 'design': 0, 't...","{'united states': 66, 'other_uncategorized': 1...","{'all': {'w9C0Znhx6QgUFVBDCwL5kQhGY93j': 81, '...","{'all': {'ClO5BpY7fpAR9MK3c0edCQXpTDN9': 130, ...","{'2010-01': {'entry': 0, 'unpaid': 0, 'senior'...",[],[],2024-08-06 14:51:23
7,FfODhCxCzBmUq11y2YbOYwVJZhEl,cubist.com,NaN,NaN,"effective january 22, 2015, cubist pharmaceuti...",cubist pharmaceuticals,linkedin.com/company/cubist-pharmaceuticals,['linkedin.com/company/cubist-pharmaceuticals'...,NaN,100,...,"{'3_month': 0.0, '6_month': 0.0, '12_month': -...","{'2010-01': 669, '2010-02': 673, '2010-03': 67...","{'2010-01': {'real_estate': 0, 'design': 0, 't...","{'united states': 86, 'germany': 3, 'south kor...","{'all': {'w9C0Znhx6QgUFVBDCwL5kQhGY93j': 173, ...","{'all': {'ClO5BpY7fpAR9MK3c0edCQXpTDN9': 240, ...","{'2010-01': {'entry': 1, 'unpaid': 0, 'senior'...",[],[],2024-08-06 14:51:23
8,bOfxIwtlJCu6LShBtCxPywZJ5Rku,msd-animal-health.com,NaN,NaN,msd animal health technology labs is where we ...,msd animal health intelligence technology labs,linkedin.com/company/msdanimalhealthintelligen...,['linkedin.com/company/msdanimalhealthtechlabs...,"['application design', 'aquaculture', 'pet act...",303,...,"{'3_month': 0.0066, '6_month': 0.0168, '12_mon...","{'2010-01': 8, '2010-02': 8, '2010-03': 8, '20...","{'2010-01': {'real_estate': 0, 'design': 0, 't...","{'israel': 203, 'united kingdom': 28, 'france'...","{'all': {'9xGgFl09gcsyBiXcV4ub4wIjEdW7': 49, '...","{'all': {'HkBLps2Nzmi5coEnHWR4hwDKXdUZ': 5, 'G...","{'2010-01': {'entry': 0, 'unpaid': 0, 'senior'...",[],[],2024-08-06 14:51:23
9,HkBLps2Nzmi5coEnHWR4hwDKXdUZ,msd.com,NaN,NaN,"at msd, known as merck & co., inc., rahway, nj...",msd,linkedin.com/company/msd-global,"['linkedin.com/company/msd-global', 'linkedin....",NaN,19657,...,"{'3_month': -0.003, '6_month': -0.0067, '12_mo...","{'2010-01': 10207, '2010-02': 10296, '2010-03'...","{'2010-01': {'real_estate': 1, 'design': 16, '...","{'ireland': 2181, 'netherlands': 1204, 'india'...","{'all': {'ClO5BpY7fpAR9MK3c0edCQXpTDN9': 3491,...","{'all': {'aHV5LA6UG4unQ3BBaA72RgYJqgwR': 1820,...","{'2010-01': {'entry': 20, 'unpaid': 0, 'senior...","[{'joined_date': '2024-02', 'pdl_id': '-AU1Pl3...",[],2024-08-06 14:51:23
10,GBmJ26BCtqdJQQHHF9J1UA7n35M8,lendingclub.com,LC,xnys,"since our founding in 2006, we have transforme...",lending club,linkedin.com/company/lending-club,"['linkedin.com/company/lending-club', 'linkedi...","['lending and investments', 'peer-to-peer lend...",1212,...,"{'3_month': -0.0057, '6_month': -0.056, '12_mo...","{'2010-01': 79, '2010-02': 83, '2010-03': 84, ...","{'2010-01': {'real_estate': 0, 'design': 2, 't...","{'united states': 1144, 'brazil': 25, 'philipp...","{'all': {'WrpKsHJ2God7yU275ANuSAuvj1FH': 375, ...","{'all': {'RjhjJnYUCiAfXFyxCHLDQQ5opPrK': 116, ...","{'2010-01': {'entry': 2, 'unpaid': 0, 'senior'...","[{'joined_date': '2024-04', 'pdl_id': 'RbHNbP0...",[],2024-08-06 14:51:23
11,CD40M2fGOEkCvAm4LQOWogcU74bg,docusign.com,DOCU,xnas,more than a million customers and a billion us...,docusign,linkedin.com/company/docusign,"['linkedin.com/company/docusign', 'linkedin.co...","['information technology', 'electronic signatu...",6960,...,"{'3_month': -0.0297, '6_month': -0.0446, '12_m...","{'2010-01': 117, '2010-02': 125, '2010-03': 13...","{'2010-01': {'real_estate': 0, 'design': 1, 't...","{'united states': 4577, 'ireland': 670, 'brazi...","{'all': {'DCD55P9HCbJ6EkJhEdPp0AFqPzf3': 849, ...","{'all': {'es7LgyqRNsFDLcWXC3WAvACHVh9g': 319, ...","{'2010-01': {'entry': 0, 'unpaid': 0, 'senior'...","[{'joined_date': '2024-05', 'pdl_id': 'PkBoaZs...","[{'departed_date': '2024-03', 'pdl_id': 'iX3io...",2024-08-06 14:51:23
12,4O9Hj7iBfxC1eJVr3pfJXgY2zY14,roche.com,RHHBF,pinx,roche is a global pioneer in pharmaceuticals a...,roche,linkedin.com/company/roche,"['linkedin.com/company/roche', 'linkedin.com/c...","['great place to work', 'innovation', 'persona...",59596,...,"{'3_month': -0.0005, '6_month': -0.0044, '12_m...","{'2010-01': 37244, '2010-02': 37252, '2010-03'...","{'2010-01': {'real_estate': 8, 'design': 86, '...","{'switzerland': 12029, 'united states': 9031, ...","{'all': {'Aefrg8G2hrDQqAhlxtUnvAWdP097': 5481,...","{'all': {'Aefrg8G2hrDQqAhlxtUnvAWdP097': 5402,...","{'2010-01': {'entry': 103, 'unpaid': 1, 'senio...","[{'joined_date': '2024-03', 'pdl_id': 'hvv9l15...","[{'departed_date': '2024-02', 'pdl_id': 'HeF8n...",2024-08-06 14:51:23
13,vJUGGoPbZ6dVbrrBwnt2swNKu91G,sigmaaldrich.com,NaN,NaN,"together with our colleagues, customers and st...",milliporesigma,linkedin.com/company/milliporesigma,"['linkedin.com/company/milliporesigma', 'linke...","['lab filtration', 'biomonitoring', 'process s...",7023,...,"{'3_month': -0.0038, '6_month': -0.0125, '12_m...","{'2010-01': 2775, '2010-02': 2768, '2010-03': ...","{'2010-01': {'real_estate': 2, 'design': 15, '...","{'united states': 6746, 'canada': 85, 'india':...","{'all': {'MQHsxfw9R2X0b9k27vHEegUZI2hf': 889, ...","{'all': {'Gk1yEjJBlLCQswdhHUrtmALGZHXD': 411, ...","{'2010-01': {'entry': 0, 'unpaid': 0, 'senior'...","[{'joined_date': '2024-04', 'pdl_id': 'vZWAwaX...","[{'departed_date': '2024-05', 'pdl_id': 'GE42s...",2024-08-06 14:51:23
14,w9C0Znhx6QgUFVBDCwL5kQhGY93j,pfizer.com,PFE.BA,xbue,pfizer is a leading research-based biopharmace...,pfizer,linkedin.com/company/pfizer,"['linkedin.com/company/pfizer', 'linkedin.com/...",['to apply science and our global resources to...,78685,...,"{'3_month': -0.0114, '6_month': -0.004, '12_mo...","{'2010-01': 77518, '2010-02': 77133, '2010-03'...","{'2010-01': {'real_estate': 15, 'design': 157,...","{'united states': 33180, 'india': 4852, 'irela...","{'all': {'KxWnnuFp5BMWIUgJFRFX3gAzDdya': 7180,...","{'all': {'Aefrg8G2hrDQqAhlxtUnvAWdP097': 9520,...","{'2010-01': {'entry': 150, 'unpaid': 5, 'senio...","[{'joined_date': '2024-02', 'pdl_id': 'Vp5Zex5...","[{'departed_date': '2024-05', 'pdl_id': 'sBIx3...",2024-08-06 14:51:23

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                102 non-null    object
 1   domain_name                       102 non-null    object
 2   ticker                            26 non-null     object
 3   mic_exchange                      24 non-null     object
 4   summary                           101 non-null    object
 5   name                              102 non-null    object
 6   linkedin_url                      102 non-null    object
 7   profiles                          102 non-null    object
 8   tags                              91 non-null     object
 9   employee_count                    102 non-null    int64
 10  website                           102 non-null    object
 11  funding_stages                    102 non-null    object
 12  funding_details                   102 non-null    object
 13  employee_growth_rate              102 non-null    object
 14  employee_count_by_month           102 non-null    object
 15  employee_count_by_month_by_role   102 non-null    object
 16  employee_count_by_country         102 non-null    object
 17  top_previous_employers_by_role    102 non-null    object
 18  top_next_employers_by_role        102 non-null    object
 19  employee_count_by_month_by_level  102 non-null    object
 20  recent_exec_hires                 102 non-null    object
 21  recent_exec_departures            102 non-null    object
 22  created_at                        102 non-null    object
dtypes: int64(1), object(22)
memory usage: 18.5+ KB

In [40]:
from ast import literal_eval
from pandas.tseries.offsets import DateOffset

In [41]:
def parse_employee_counts(employee_count_str):
    try:
        return literal_eval(employee_count_str)
    except:
        return {}

df['employee_count_by_month_by_role_parsed'] = df['employee_count_by_month_by_role'].apply(parse_employee_counts)
#parsing in each row

In [42]:
def extract_sales_data(employee_data):
    sales_data = {}
    for month, roles in employee_data.items():
        if 'sales' in roles:
            sales_data[month] = roles['sales']
    return sales_data

df['sales_data'] = df['employee_count_by_month_by_role_parsed'].apply(extract_sales_data)

In [43]:
df[['domain_name', 'sales_data']].head()
#'extracted sales data'

     domain_name                                         sales_data
0  hellosign.com  {'2010-01': 0, '2010-02': 0, '2010-03': 0, '20...
1   unilever.com  {'2010-01': 6106, '2010-02': 6173, '2010-03': ...
2     vmware.com  {'2010-01': 1157, '2010-02': 1156, '2010-03': ...
3  medtronic.com  {'2010-01': 5101, '2010-02': 5124, '2010-03': ...
4   novartis.com  {'2010-01': 7996, '2010-02': 7999, '2010-03': ...

In [44]:
def calculate_sales_decline(sales_data):
    # Convert the dictionary into a pandas DataFrame for easier processing
    sales_df = pd.DataFrame(list(sales_data.items()), columns=['month', 'count'])
    sales_df['month'] = pd.to_datetime(sales_df['month'], format='%Y-%m')
    sales_df = sales_df.set_index('month').sort_index()

    # Get the last date from the dataset
    last_date = sales_df.index.max()

    # Get the date 6 months before the last date
    six_months_ago = last_date - DateOffset(months=6)

    # Filter sales data to only include the last 6 months
    recent_sales = sales_df[sales_df.index > six_months_ago]

    if not recent_sales.empty:
        start_count = recent_sales.iloc[0]['count']
        end_count = recent_sales.iloc[-1]['count']

        # Calculate absolute and relative decline
        absolute_decline = end_count - start_count
        if start_count != 0:
            relative_decline = (absolute_decline / start_count) * 100
        else:
            relative_decline = float('nan')  # Handle the case where start_count is zero

        return start_count, end_count, absolute_decline, relative_decline
    return None, None, None, None

In [86]:
# Apply the function to each row
df['start_sales'], df['end_sales'], df['absolute_decline'], df['relative_decline'] = zip(*df['sales_data'].apply(calculate_sales_decline))

# Display the results (showing top 5 for verification)
print(df[['domain_name', 'start_sales', 'end_sales', 'absolute_decline', 'relative_decline']].head())

     domain_name  start_sales  end_sales  absolute_decline  relative_decline
0  hellosign.com            1          1                 0          0.000000
1   unilever.com         8721       8665               -56         -0.642128
2     vmware.com         3421       2631              -790        -23.092663
3  medtronic.com         9144       9109               -35         -0.382765
4   novartis.com         4163       4086               -77         -1.849628

In [46]:
# Find the company with the largest relative decline
largest_relative_decline = df.loc[df['relative_decline'].idxmin()]

In [64]:
print(f"Company with the largest relative sales decline: {largest_relative_decline['domain_name']}")
print(f"Relative Decline: {largest_relative_decline['relative_decline']}%")
print(f"Start Sales: {largest_relative_decline['start_sales']}, End Sales: {largest_relative_decline['end_sales']}")

Company with the largest relative sales decline: grom.it
Relative Decline: -66.66666666666666%
Start Sales: 3, End Sales: 1

##Writing start date and end date

In [48]:
import pandas as pd
from pandas.tseries.offsets import DateOffset

# Define the function to calculate sales decline (using fixed date range)
def calculate_sales_decline(sales_data):
    # Convert the dictionary into a pandas DataFrame for easier processing
    sales_df = pd.DataFrame(list(sales_data.items()), columns=['month', 'count'])
    sales_df['month'] = pd.to_datetime(sales_df['month'], format='%Y-%m')
    sales_df = sales_df.set_index('month').sort_index()

    # Define the start date (2010-01) and end date (2024-05)
    start_date = pd.to_datetime('2010-01')
    end_date = pd.to_datetime('2024-05')

    # Get the last 6 months before the end date
    six_months_ago = end_date - DateOffset(months=6)

    # Filter sales data within the defined date range (last 6 months before end date)
    recent_sales = sales_df[(sales_df.index > six_months_ago) & (sales_df.index <= end_date)]

    if not recent_sales.empty:
        start_count = recent_sales.iloc[0]['count']
        end_count = recent_sales.iloc[-1]['count']

        # Calculate absolute and relative decline
        absolute_decline = end_count - start_count
        if start_count != 0:
            relative_decline = (absolute_decline / start_count) * 100
        else:
            relative_decline = float('nan')  # Handle the case where start_count is zero

        return start_count, end_count, absolute_decline, relative_decline
    return None, None, None, None

# Assuming 'df' is the DataFrame with your data and 'sales_data' is a column with sales info

# Apply the function to each row
df['start_sales'], df['end_sales'], df['absolute_decline'], df['relative_decline'] = zip(*df['sales_data'].apply(calculate_sales_decline))

# Display the results (showing top 5 for verification)
print(df[['domain_name', 'start_sales', 'end_sales', 'absolute_decline', 'relative_decline']].head())

# Find the company with the largest relative decline
largest_relative_decline = df.loc[df['relative_decline'].idxmin()]

# Print the company with the largest relative decline
print(f"Company with the largest relative sales decline: {largest_relative_decline['domain_name']}")
print(f"Relative Decline: {largest_relative_decline['relative_decline']}%")
print(f"Start Sales: {largest_relative_decline['start_sales']}, End Sales: {largest_relative_decline['end_sales']}")

     domain_name  start_sales  end_sales  absolute_decline  relative_decline
0  hellosign.com            1          1                 0          0.000000
1   unilever.com         8721       8665               -56         -0.642128
2     vmware.com         3421       2631              -790        -23.092663
3  medtronic.com         9144       9109               -35         -0.382765
4   novartis.com         4163       4086               -77         -1.849628
Company with the largest relative sales decline: grom.it
Relative Decline: -66.66666666666666%
Start Sales: 3, End Sales: 1

We should consider Relative Decline. Relative decline is generally better analysis as it works good when companies are of different size.
It is relatively good for doing broader comparisons. It provides a percentage change that is more comparable across different organizations.

## B
Which companies have a recent executive arrival/departures in engineering teams ?
Create a dataframe with the columns: website x title x date joined x movement_type (arrival/departure)

In [16]:
from ast import literal_eval

In [17]:
def parse_exec_data(exec_str):
    try:
        return literal_eval(exec_str)
    except:
        return []

In [18]:
df['recent_exec_hires_parsed'] = df['recent_exec_hires'].apply(parse_exec_data)
df['recent_exec_departures_parsed'] = df['recent_exec_departures'].apply(parse_exec_data)

In [19]:
def extract_movements(exec_data, movement_type, website):
    movements = []
    for entry in exec_data:
        job_title = entry['job_title'].lower()
        if 'engineering' in job_title or 'technology' in job_title:
            movements.append({
                'website': website,
                'title': entry['job_title'],
                'date_joined': entry.get('joined_date') if movement_type == 'arrival' else entry.get('departed_date'),
                'movement_type': movement_type
            })
    return movements

In [20]:
engineering_movements = []
for idx, row in df.iterrows():
    engineering_movements += extract_movements(row['recent_exec_hires_parsed'], 'arrival', row['website'])
    engineering_movements += extract_movements(row['recent_exec_departures_parsed'], 'departure', row['website'])

In [21]:
engineering_movements_df = pd.DataFrame(engineering_movements)
print(engineering_movements_df)

         website                                              title  \
0   unilever.com        chief technology officer - digital ventures
1     vmware.com                   channel chief technology officer
2     vmware.com                chief technology officer ambassador
3     vmware.com                     cloud chief technology officer
4     vmware.com  vice president and chief technology officer, a...
5     vmware.com  vice president - products, technology and cust...
6     vmware.com  vice president and chief technology officer, a...
7   docusign.com  vice president, cloud engineering and technica...
8     pfizer.com    vice president process chemistry and technology
9     pfizer.com                          technology owner building
10        pg.com          dry laundry tower global technology owner
11        pg.com  senior vice president - supply chain innovatio...
12        pg.com            chief technology officer, tide cleaners
13     dlrshv.es                       vice president of technology
14    citrix.com  vice president,global support engineering, tam...
15    seagen.com       vice president, core research and technology
16  flatiron.com       software engineering vice president, techops

   date_joined movement_type
0      2024-04     departure
1      2024-05       arrival
2      2024-02     departure
3      2024-03     departure
4      2024-02     departure
5      2024-03     departure
6      2024-02     departure
7      2024-03       arrival
8      2024-02       arrival
9      2024-04       arrival
10     2024-04       arrival
11     2024-03       arrival
12     2024-05     departure
13     2024-02     departure
14     2024-03     departure
15     2024-02     departure
16     2024-04     departure

In [22]:
engineering_movements_df.to_csv('output_table.csv', index=False)
pd.read_csv('output_table.csv')

,website,title,date_joined,movement_type
0,unilever.com,chief technology officer - digital ventures,2024-04,departure
1,vmware.com,channel chief technology officer,2024-05,arrival
2,vmware.com,chief technology officer ambassador,2024-02,departure
3,vmware.com,cloud chief technology officer,2024-03,departure
4,vmware.com,"vice president and chief technology officer, a...",2024-02,departure
5,vmware.com,"vice president - products, technology and cust...",2024-03,departure
6,vmware.com,"vice president and chief technology officer, a...",2024-02,departure
7,docusign.com,"vice president, cloud engineering and technica...",2024-03,arrival
8,pfizer.com,vice president process chemistry and technology,2024-02,arrival
9,pfizer.com,technology owner building,2024-04,arrival
10,pg.com,dry laundry tower global technology owner,2024-04,arrival
11,pg.com,senior vice president - supply chain innovatio...,2024-03,arrival
12,pg.com,"chief technology officer, tide cleaners",2024-05,departure
13,dlrshv.es,vice president of technology,2024-02,departure
14,citrix.com,"vice president,global support engineering, tam...",2024-03,departure
15,seagen.com,"vice president, core research and technology",2024-02,departure
16,flatiron.com,"software engineering vice president, techops",2024-04,departure

##Score

Simple Scaling from 0 to 10

In [23]:
import pandas as pd
import numpy as np
from pandas.tseries.offsets import DateOffset

#Parse sales data and calculate absolute and relative deltas
def extract_sales_data(row):
    sales_data = row['employee_count_by_month_by_role']
    sales_data = eval(sales_data)
    sales_team_data = {k: v.get('sales', 0) for k, v in sales_data.items()}  # Extract sales data
    return sales_team_data

def calculate_sales_deltas(sales_data):
    sales_df = pd.DataFrame(list(sales_data.items()), columns=['month', 'sales'])
    sales_df['month'] = pd.to_datetime(sales_df['month'], format='%Y-%m')
    sales_df = sales_df.set_index('month').sort_index()

    most_recent_date = sales_df.index[-1]
    six_months_ago = most_recent_date - DateOffset(months=6)
    recent_sales = sales_df[sales_df.index > six_months_ago]

    if not recent_sales.empty:
        start_sales = recent_sales.iloc[0]['sales']
        end_sales = recent_sales.iloc[-1]['sales']

        #Calculate absolute and relative delta
        absolute_delta = end_sales - start_sales
        relative_delta = (absolute_delta / start_sales) if start_sales != 0 else float('nan')

        return start_sales, end_sales, absolute_delta, relative_delta
    return None, None, None, None

def normalize_relative_delta(relative_delta):
    return (relative_delta + 1) / 2

def normalize_size(size, max_size):
    return size / max_size

#health score
def calculate_health_score(row, max_size):
    _, end_sales, absolute_delta, relative_delta = calculate_sales_deltas(row['sales_data'])
    if end_sales is not None:
        norm_relative_delta = normalize_relative_delta(relative_delta)
        norm_size = normalize_size(end_sales, max_size)

        score = 0.6 * norm_relative_delta + 0.4 * norm_size
        return score * 10
    return 0

df = pd.read_csv('/content/sample_data/pdl_file.csv')

df['sales_data'] = df.apply(extract_sales_data, axis=1)

max_size = df['sales_data'].apply(lambda x: max(x.values())).max()

df['Health Score'] = df.apply(lambda row: calculate_health_score(row, max_size), axis=1)

max_score_row = df.loc[df['Health Score'].idxmax()]
print(f"Company with highest health score: {max_score_row['name']} with a score of {max_score_row['Health Score']}")

print(df[['name', 'Health Score']])

Company with highest health score: medtronic with a score of 6.8295459450396026
                               name  Health Score
0                         hellosign      3.000422
1                          unilever      6.634542
2                            vmware      3.416645
3                         medtronic      6.829546
4                          novartis      4.667471
..                              ...           ...
97                            alcon      3.806935
98                           sandoz      3.543138
99                    sandoz france      3.002530
100           the medicines company      3.002952
101  havana club international s.a.      3.000843

[102 rows x 2 columns]

Percentile scaling

In [81]:
import pandas as pd
import numpy as np
from pandas.tseries.offsets import DateOffset

# Parse sales data and calculate absolute and relative deltas
def extract_sales_data(row):
    sales_data = row['employee_count_by_month_by_role']
    sales_data = eval(sales_data)
    sales_team_data = {k: v.get('sales', 0) for k, v in sales_data.items()}  # Extract sales data
    return sales_team_data

def calculate_sales_deltas(sales_data):
    sales_df = pd.DataFrame(list(sales_data.items()), columns=['month', 'sales'])
    sales_df['month'] = pd.to_datetime(sales_df['month'], format='%Y-%m')
    sales_df = sales_df.set_index('month').sort_index()

    most_recent_date = sales_df.index[-1]
    six_months_ago = most_recent_date - DateOffset(months=6)
    recent_sales = sales_df[sales_df.index > six_months_ago]

    if not recent_sales.empty:
        start_sales = recent_sales.iloc[0]['sales']
        end_sales = recent_sales.iloc[-1]['sales']

        # Calculate absolute and relative delta
        absolute_delta = end_sales - start_sales
        relative_delta = (absolute_delta / start_sales) if start_sales != 0 else float('nan')

        return start_sales, end_sales, absolute_delta, relative_delta
    return None, None, None, None

def normalize_with_percentiles(value, lower_percentile, upper_percentile):
    """Normalize a value to a scale of 0 to 10 based on lower and upper percentiles."""
    if value < lower_percentile:
        return 0
    elif value > upper_percentile:
        return 10
    else:
        return 10 * (value - lower_percentile) / (upper_percentile - lower_percentile)

# Health score calculation
def calculate_health_score(row, lower_percentile_size, upper_percentile_size, lower_percentile_delta, upper_percentile_delta):
    _, end_sales, absolute_delta, relative_delta = calculate_sales_deltas(row['sales_data'])
    if end_sales is not None:
        norm_relative_delta = normalize_with_percentiles(relative_delta, lower_percentile_delta, upper_percentile_delta)
        norm_size = normalize_with_percentiles(end_sales, lower_percentile_size, upper_percentile_size)

        # Weighted average score
        score = 0.6 * norm_relative_delta + 0.4 * norm_size
        return score
    return 0

# Load the DataFrame
df = pd.read_csv('/content/sample_data/pdl_file.csv')

df['sales_data'] = df.apply(extract_sales_data, axis=1)

# Calculate sales values and their statistics for normalization
sales_values = df['sales_data'].apply(lambda x: max(x.values())).dropna()
lower_percentile_size = sales_values.quantile(0.1)
upper_percentile_size = sales_values.quantile(0.9)

# Calculate relative deltas for normalization
relative_deltas = df.apply(lambda row: calculate_sales_deltas(row['sales_data'])[3], axis=1)
lower_percentile_delta = relative_deltas.quantile(0.1)
upper_percentile_delta = relative_deltas.quantile(0.9)

# Apply the health score calculation
df['Health Score'] = df.apply(lambda row: calculate_health_score(row, lower_percentile_size, upper_percentile_size, lower_percentile_delta, upper_percentile_delta), axis=1)

# Find the company with the highest health score
max_score_row = df.loc[df['Health Score'].idxmax()]
print(f"Company with highest health score: {max_score_row['name']} with a score of {max_score_row['Health Score']}")

print(df[['name', 'Health Score']])

Company with highest health score: boston scientific with a score of 7.736770010066715
                               name  Health Score
0                         hellosign      3.380633
1                          unilever      7.170953
2                            vmware      4.000000
3                         medtronic      7.255645
4                          novartis      6.776658
..                              ...           ...
97                            alcon      6.705163
98                           sandoz      5.492374
99                    sandoz france      3.380633
100           the medicines company      3.380633
101  havana club international s.a.      3.380633

[102 rows x 2 columns]

10th percentile (P10) as the minimum and the 90th percentile (P90) as the maximum for normalization:

In [70]:
import pandas as pd
import numpy as np
from pandas.tseries.offsets import DateOffset

# Parse sales data and calculate absolute and relative deltas
def extract_sales_data(row):
    sales_data = row['employee_count_by_month_by_role']
    sales_data = eval(sales_data)
    sales_team_data = {k: v.get('sales', 0) for k, v in sales_data.items()}  # Extract sales data
    return sales_team_data

def calculate_sales_deltas(sales_data):
    sales_df = pd.DataFrame(list(sales_data.items()), columns=['month', 'sales'])
    sales_df['month'] = pd.to_datetime(sales_df['month'], format='%Y-%m')
    sales_df = sales_df.set_index('month').sort_index()

    most_recent_date = sales_df.index[-1]
    six_months_ago = most_recent_date - DateOffset(months=6)
    recent_sales = sales_df[sales_df.index > six_months_ago]

    if not recent_sales.empty:
        start_sales = recent_sales.iloc[0]['sales']
        end_sales = recent_sales.iloc[-1]['sales']

        # Calculate absolute and relative delta
        absolute_delta = end_sales - start_sales
        relative_delta = (absolute_delta / start_sales) if start_sales != 0 else float('nan')

        return start_sales, end_sales, absolute_delta, relative_delta
    return None, None, None, None

def normalize_with_p10_p90(value, p10, p90):
    """Normalize a value to a scale of 0 to 10 based on P10 and P90."""
    if value < p10:
        return 0
    elif value > p90:
        return 10
    else:
        return 10 * (value - p10) / (p90 - p10)

# Health score calculation
def calculate_health_score(row, p10_size, p90_size, p10_delta, p90_delta):
    _, end_sales, absolute_delta, relative_delta = calculate_sales_deltas(row['sales_data'])
    if end_sales is not None:
        norm_relative_delta = normalize_with_p10_p90(relative_delta, p10_delta, p90_delta)
        norm_size = normalize_with_p10_p90(end_sales, p10_size, p90_size)

        # Weighted average score
        score = 0.6 * norm_relative_delta + 0.4 * norm_size
        return score
    return 0

# Load the DataFrame
df = pd.read_csv('/content/sample_data/pdl_file.csv')

df['sales_data'] = df.apply(extract_sales_data, axis=1)

# Calculate sales values and their statistics for normalization
sales_values = df['sales_data'].apply(lambda x: max(x.values())).dropna()
p10_size = sales_values.quantile(0.1)
p90_size = sales_values.quantile(0.9)

# Calculate relative deltas for normalization
relative_deltas = df.apply(lambda row: calculate_sales_deltas(row['sales_data'])[3], axis=1)
p10_delta = relative_deltas.quantile(0.1)
p90_delta = relative_deltas.quantile(0.9)

# Apply the health score calculation
df['Health Score'] = df.apply(lambda row: calculate_health_score(row, p10_size, p90_size, p10_delta, p90_delta), axis=1)

# Find the company with the highest health score
max_score_row = df.loc[df['Health Score'].idxmax()]
print(f"Company with highest health score: {max_score_row['name']} with a score of {max_score_row['Health Score']}")

print(df[['name', 'Health Score']])

Company with highest health score: boston scientific with a score of 7.736770010066715
                               name  Health Score
0                         hellosign      3.380633
1                          unilever      7.170953
2                            vmware      4.000000
3                         medtronic      7.255645
4                          novartis      6.776658
..                              ...           ...
97                            alcon      6.705163
98                           sandoz      5.492374
99                    sandoz france      3.380633
100           the medicines company      3.380633
101  havana club international s.a.      3.380633

[102 rows x 2 columns]

Set start and end date

In [87]:
import pandas as pd
import numpy as np
from pandas.tseries.offsets import DateOffset

# Define the fixed date range
START_DATE = pd.to_datetime('2010-01')
END_DATE = pd.to_datetime('2024-05')

# Parse sales data and calculate absolute and relative deltas
def extract_sales_data(row):
    sales_data = row['employee_count_by_month_by_role']
    sales_data = eval(sales_data)
    sales_team_data = {k: v.get('sales', 0) for k, v in sales_data.items()}  # Extract sales data
    return sales_team_data

def calculate_sales_deltas(sales_data):
    sales_df = pd.DataFrame(list(sales_data.items()), columns=['month', 'sales'])
    sales_df['month'] = pd.to_datetime(sales_df['month'], format='%Y-%m')
    sales_df = sales_df.set_index('month').sort_index()

    # Filter sales data to only include the specified date range
    sales_df = sales_df[(sales_df.index >= START_DATE) & (sales_df.index <= END_DATE)]

    if not sales_df.empty:
        start_sales = sales_df.iloc[0]['sales']
        end_sales = sales_df.iloc[-1]['sales']

        # Calculate absolute and relative delta
        absolute_delta = end_sales - start_sales
        relative_delta = (absolute_delta / start_sales) if start_sales != 0 else float('nan')

        return start_sales, end_sales, absolute_delta, relative_delta
    return None, None, None, None

def normalize_with_p10_p90(value, p10, p90):
    """Normalize a value to a scale of 0 to 10 based on P10 and P90."""
    if value < p10:
        return 0
    elif value > p90:
        return 10
    else:
        return 10 * (value - p10) / (p90 - p10)

# Health score calculation
def calculate_health_score(row, p10_size, p90_size, p10_delta, p90_delta):
    _, end_sales, absolute_delta, relative_delta = calculate_sales_deltas(row['sales_data'])
    if end_sales is not None:
        norm_relative_delta = normalize_with_p10_p90(relative_delta, p10_delta, p90_delta)
        norm_size = normalize_with_p10_p90(end_sales, p10_size, p90_size)

        # Weighted average score
        score = 0.6 * norm_relative_delta + 0.4 * norm_size
        return score
    return 0

# Load the DataFrame
df = pd.read_csv('/content/sample_data/pdl_file.csv')

df['sales_data'] = df.apply(extract_sales_data, axis=1)

# Calculate sales values and their statistics for normalization
sales_values = df['sales_data'].apply(lambda x: max(x.values())).dropna()
p10_size = sales_values.quantile(0.1)
p90_size = sales_values.quantile(0.9)

# Calculate relative deltas for normalization
relative_deltas = df.apply(lambda row: calculate_sales_deltas(row['sales_data'])[3], axis=1)
p10_delta = relative_deltas.quantile(0.1)
p90_delta = relative_deltas.quantile(0.9)

# Apply the health score calculation
df['Health Score'] = df.apply(lambda row: calculate_health_score(row, p10_size, p90_size, p10_delta, p90_delta), axis=1)

# Find the company with the highest health score
max_score_row = df.loc[df['Health Score'].idxmax()]
print(f"Company with highest health score: {max_score_row['name']} with a score of {max_score_row['Health Score']}")

print(df[['name', 'Health Score']])

Company with highest health score: docusign with a score of 9.006798648821995
                               name  Health Score
0                         hellosign           NaN
1                          unilever      4.878370
2                            vmware      5.569965
3                         medtronic      5.174971
4                          novartis      4.143735
..                              ...           ...
97                            alcon      3.898173
98                           sandoz      3.391799
99                    sandoz france      4.584270
100           the medicines company      0.000000
101  havana club international s.a.      1.348315

[102 rows x 2 columns]

Taking start date and end date by itself

In [88]:
import pandas as pd
import numpy as np
from pandas.tseries.offsets import DateOffset

# Parse sales data and calculate absolute and relative deltas
def extract_sales_data(row):
    sales_data = row['employee_count_by_month_by_role']
    sales_data = eval(sales_data)
    sales_team_data = {k: v.get('sales', 0) for k, v in sales_data.items()}
    return sales_team_data

def calculate_sales_deltas(sales_data):
    sales_df = pd.DataFrame(list(sales_data.items()), columns=['month', 'sales'])
    sales_df['month'] = pd.to_datetime(sales_df['month'], format='%Y-%m')
    sales_df = sales_df.set_index('month').sort_index()

    # Get the most recent and 6 months ago dates
    most_recent_date = sales_df.index[-1]
    six_months_ago_date = most_recent_date - DateOffset(months=6)

    # Get sales data within the last 6 months
    six_months_ago_sales = sales_df.loc[sales_df.index <= six_months_ago_date]
    recent_sales = sales_df.loc[sales_df.index >= most_recent_date]

    if not six_months_ago_sales.empty and not recent_sales.empty:
        start_sales = six_months_ago_sales.iloc[-1]['sales']
        end_sales = recent_sales.iloc[-1]['sales']

        # Calculate absolute and relative delta
        absolute_delta = end_sales - start_sales
        relative_delta = (absolute_delta / start_sales) if start_sales != 0 else float('nan')

        return start_sales, end_sales, absolute_delta, relative_delta
    return None, None, None, None

def normalize_with_p10_p90(value, p10, p90):
    """Normalize a value to a scale of 0 to 10 based on P10 and P90."""
    if value < p10:
        return 0
    elif value > p90:
        return 10
    else:
        return 10 * (value - p10) / (p90 - p10)

# Health score calculation
def calculate_health_score(row, p10_size, p90_size, p10_delta, p90_delta):
    _, end_sales, absolute_delta, relative_delta = calculate_sales_deltas(row['sales_data'])
    if end_sales is not None:
        norm_relative_delta = normalize_with_p10_p90(relative_delta, p10_delta, p90_delta)
        norm_size = normalize_with_p10_p90(end_sales, p10_size, p90_size)

        # Weighted average score
        score = 0.6 * norm_relative_delta + 0.4 * norm_size
        return score
    return 0

# Load the DataFrame
df = pd.read_csv('/content/sample_data/pdl_file.csv')

df['sales_data'] = df.apply(extract_sales_data, axis=1)

# Calculate sales values and their statistics for normalization
sales_values = df['sales_data'].apply(lambda x: max(x.values())).dropna()
p10_size = sales_values.quantile(0.1)
p90_size = sales_values.quantile(0.9)

# Calculate relative deltas for normalization
relative_deltas = df.apply(lambda row: calculate_sales_deltas(row['sales_data'])[3], axis=1)
p10_delta = relative_deltas.quantile(0.1)
p90_delta = relative_deltas.quantile(0.9)

# Apply the health score calculation
df['Health Score'] = df.apply(lambda row: calculate_health_score(row, p10_size, p90_size, p10_delta, p90_delta), axis=1)

# Find the company with the highest health score
max_score_row = df.loc[df['Health Score'].idxmax()]
print(f"Company with highest health score: {max_score_row['name']} with a score of {max_score_row['Health Score']}")

# Print company with biggest relative and absolute decline
df['Absolute Decline'] = df['sales_data'].apply(lambda x: calculate_sales_deltas(x)[2])
df['Relative Decline'] = df['sales_data'].apply(lambda x: calculate_sales_deltas(x)[3])

# Company with biggest absolute decline
biggest_abs_decline = df.loc[df['Absolute Decline'].idxmin()]
print(f"Company with biggest absolute decline: {biggest_abs_decline['name']} with a decline of {biggest_abs_decline['Absolute Decline']}")

# Company with biggest relative decline
biggest_rel_decline = df.loc[df['Relative Decline'].idxmin()]
print(f"Company with biggest relative decline: {biggest_rel_decline['name']} with a decline of {biggest_rel_decline['Relative Decline']}")

print(df[['name', 'Health Score', 'Absolute Decline', 'Relative Decline']])

Company with highest health score: boston scientific with a score of 8.369125535941537
Company with biggest absolute decline: vmware with a decline of -1105
Company with biggest relative decline: grom with a decline of -0.75
                               name  Health Score  Absolute Decline  \
0                         hellosign      4.050369                 0
1                          unilever      7.863900               -67
2                            vmware      4.000000             -1105
3                         medtronic      7.899243               -57
4                          novartis      7.481149               -98
..                              ...           ...               ...
97                            alcon      7.219664                -4
98                           sandoz      6.084197               -11
99                    sandoz france      4.050369                 0
100           the medicines company      4.050369                 0
101  havana club international s.a.      4.050369                 0

     Relative Decline
0            0.000000
1           -0.007673
2           -0.295771
3           -0.006219
4           -0.023423
..                ...
97          -0.002111
98          -0.008296
99           0.000000
100          0.000000
101          0.000000

[102 rows x 4 columns]

#Sample Dataset

In [ ]:
import pandas as pd

In [ ]:
data = {
    'account': ['ABC', 'BCD', 'FGH', 'DEF', 'CDE', 'EFG', 'PQR', 'XYZ'],
    '2024-03': [100, 90, 10, 500, 1000, 400, 500, 1000000],
    '2024-09': [120, 104, 20, 420, 800, 200, 250, 990000],
    'Relative Delta': [0.20, 0.16, 1.00, -0.16, -0.20, -0.50, -0.50, -0.01],
    'Absolute Delta': [20, 14, 10, -80, -200, -200, -250, -10000]
       }

In [ ]:
df = pd.DataFrame(data)
df

  account  2024-03  2024-09  Relative Delta  Absolute Delta
0     ABC      100      120            0.20              20
1     BCD       90      104            0.16              14
2     FGH       10       20            1.00              10
3     DEF      500      420           -0.16             -80
4     CDE     1000      800           -0.20            -200
5     EFG      400      200           -0.50            -200
6     PQR      500      250           -0.50            -250
7     XYZ  1000000   990000           -0.01          -10000

In [ ]:
def normalize_relative_delta(relative_delta):
    return ((relative_delta + 0.5) / 1.5) * 10
#normalized relative delta

In [ ]:
max_size = df['2024-09'].max()
def normalize_size(size, max_size):
    return (size / max_size) * 10
#normalized size

In [ ]:
def calculate_health_score(row, max_size):
    norm_relative_delta = normalize_relative_delta(row['Relative Delta'])
    norm_size = normalize_size(row['2024-09'], max_size)
    score = 0.6 * norm_relative_delta + 0.4 * norm_size
    return score
#Health score by emphasizing relative delta

In [ ]:
df['Health Score'] = df.apply(lambda row: calculate_health_score(row, max_size), axis=1)
print(df[['account', 'Health Score']])

  account  Health Score
0     ABC      2.800485
1     BCD      2.640420
2     FGH      6.000081
3     DEF      1.361697
4     CDE      1.203232
5     EFG      0.000808
6     PQR      0.001010
7     XYZ      5.960000

In [ ]:
def calculate_health_score_weighted_size(row, max_size):
    norm_relative_delta = normalize_relative_delta(row['Relative Delta'])
    norm_size = normalize_size(row['2024-09'], max_size)
    score = 0.4 * norm_relative_delta + 0.6 * norm_size
    return score
#Health score by emphasizing absolute size

In [ ]:
df['Health Score (Weighted Size)'] = df.apply(lambda row: calculate_health_score_weighted_size(row, max_size), axis=1)
print(df[['account', 'Health Score (Weighted Size)']])

  account  Health Score (Weighted Size)
0     ABC                      1.867394
1     BCD                      1.760630
2     FGH                      4.000121
3     DEF                      0.909212
4     CDE                      0.804848
5     EFG                      0.001212
6     PQR                      0.001515
7     XYZ                      7.306667

In [ ]:
print(df[['account','2024-03','2024-09','Relative Delta',	'Absolute Delta', 'Health Score (Weighted Size)','Health Score' ]])

  account  2024-03  2024-09  Relative Delta  Absolute Delta  \
0     ABC      100      120            0.20              20
1     BCD       90      104            0.16              14
2     FGH       10       20            1.00              10
3     DEF      500      420           -0.16             -80
4     CDE     1000      800           -0.20            -200
5     EFG      400      200           -0.50            -200
6     PQR      500      250           -0.50            -250
7     XYZ  1000000   990000           -0.01          -10000

   Health Score (Weighted Size)  Health Score
0                      1.867394      2.800485
1                      1.760630      2.640420
2                      4.000121      6.000081
3                      0.909212      1.361697
4                      0.804848      1.203232
5                      0.001212      0.000808
6                      0.001515      0.001010
7                      7.306667      5.960000

In [ ]:
df

,account,2024-03,2024-09,Relative Delta,Absolute Delta,Health Score,Health Score (Weighted Size)
0,ABC,100,120,0.20,20,2.800485,1.867394
1,BCD,90,104,0.16,14,2.640420,1.760630
2,FGH,10,20,1.00,10,6.000081,4.000121
3,DEF,500,420,-0.16,-80,1.361697,0.909212
4,CDE,1000,800,-0.20,-200,1.203232,0.804848
5,EFG,400,200,-0.50,-200,0.000808,0.001212
6,PQR,500,250,-0.50,-250,0.001010,0.001515
7,XYZ,1000000,990000,-0.01,-10000,5.960000,7.306667